# Generated by Django 5.2.4 on 2025-07-30 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0003_discount_tax_order_price_after_discount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="items.item", verbose_name="Items"),
        ),
    ]
