# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0004_alter_order_items"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="discount",
            options={
                "ordering": ["pk"],
                "verbose_name": "Скидка",
                "verbose_name_plural": "Скидки",
            },
        ),
        migrations.AlterModelOptions(
            name="tax",
            options={
                "ordering": ["pk"],
                "verbose_name": "Налог",
                "verbose_name_plural": "Налоги",
            },
        ),
        migrations.AlterModelTable(
            name="discount",
            table="items_discount",
        ),
        migrations.AlterModelTable(
            name="tax",
            table="items_tax",
        ),
    ]
