# Generated by Django 5.2.4 on 2025-07-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0005_alter_discount_options_alter_tax_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="percents",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Discount percents"
            ),
        ),
        migrations.AlterField(
            model_name="tax",
            name="percents",
            field=models.DecimalField(
                decimal_places=2, max_digits=5, verbose_name="Tax percents"
            ),
        ),
    ]
