# Generated by Django 5.2.4 on 2025-07-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0006_alter_discount_percents_alter_tax_percents"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="price_currency",
            field=models.CharField(
                choices=[("USD", "US Dollars"), ("RUB", "Ruble")],
                default="USD",
                max_length=3,
                verbose_name="Currency",
            ),
        ),
    ]
