# Generated by Django 5.2.4 on 2025-07-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("items", "0007_order_price_currency"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="price_currency",
            new_name="currency",
        ),
    ]
